Feature/sc 105371 kubernetes 1 26
dataiku/dss-plugin-gke-clusters pull request #20
Opened 2022-11-25 15:07 UTC by amandineslx

2022-11-28 08:15 UTC, jules-casoli requested changes
Lacks the CHANGELOG.
Also, I didn't realise that legacy-auth was a `client-facing` option. Meaning it's removal is a bit more impacting than I though. Should we put it in a separate PR then ?

2022-11-28 08:15 UTC, jules-casoli commented on python-lib/dku_google/gcloud.py
> +        for the specified cluster
```suggestion
        for the specified cluster, and creates an adequate kubeconfig file.
```

2022-12-14 12:29 UTC, marchelleboid requested changes
Tested with clusters on version 1.21 and 1.24 (oldest and newest available on GKE), and it works.

I'm wondering about the new step to install the "auth plugin". For DSS provisioned by FM, that's easy enough for add so it's transparent to the users, but what about users who aren't using FM? Can we make it clear enough for them that there's an additional manual step of installing the auth plugin, or else creating new clusters won't work with this version of the cluster plugin? I see that the auth plugin can be installed directly by a `gcloud` command, even if it's not the recommended way for Linux, could the cluster plugin itself try to do this? (for example in the EKS plugin, it installs `eksctl` if it can't find it)

2022-12-14 14:55 UTC, amandineslx commented
> I'm wondering about the new step to install the "auth plugin". For DSS provisioned by FM, that's easy enough for add so it's transparent to the users, but what about users who aren't using FM? Can we make it clear enough for them that there's an additional manual step of installing the auth plugin, or else creating new clusters won't work with this version of the cluster plugin? I see that the auth plugin can be installed directly by a `gcloud` command, even if it's not the recommended way for Linux, could the cluster plugin itself try to do this? (for example in the EKS plugin, it installs `eksctl` if it can't find it)

The error message is quite explicit about the missing executable. However, we can add to the documentation about elastic setups that the user needs to make sure this plugin is installed on the DSS machine before trying to spin up the cluster.

About the ad hoc installation, `dataiku` user is not a sudoer on the machine and cannot run the `yum install` command documented in the installation guide. Also, `gcloud` installation command does not work as the component manager seems to be disabled on the machine.

2022-12-15 11:37 UTC, marchelleboid commented
> The error message is quite explicit about the missing executable. However, we can add to the documentation about elastic setups that the user needs to make sure this plugin is installed on the DSS machine before trying to spin up the cluster.
> 
> About the ad hoc installation, `dataiku` user is not a sudoer on the machine and cannot run the `yum install` command documented in the installation guide. Also, `gcloud` installation command does not work as the component manager seems to be disabled on the machine.

That makes sense to me (even trying a yum install would be complicated because you would need to figure out if yum is even the correct package manager to use). It's true that in our documentation, we already tell the user that they must have `gcloud`, `docker`, and `kubectl` installed, so this auth plugin can also be added there

2022-12-15 13:38 UTC, marchelleboid approved these changes

2022-12-20 10:47 UTC, amandineslx commented
@marchelleboid if you want to have a look at the changelog, it has been updated now :)

2022-12-20 10:49 UTC, jules-casoli approved these changes

2022-12-20 10:54 UTC, marchelleboid approved these changes

2022-12-21 20:36 UTC, alex-dataiku approved these changes
LGTM:
- successfully attached cluster in version `v1.23.12-gke.100`
- successfully created cluster in version `v1.25.4-gke.2100`

2022-12-22 13:08 UTC, merged