Fix example CIDR block [sc-92162]
dataiku/dss-plugin-gke-clusters pull request #29
Opened 2023-08-09 15:58 UTC by marchelleboid

[sc-92162]

2023-08-09 18:03 UTC, amandineslx requested changes
just to make sure it was not forgotten

2023-08-09 18:03 UTC, amandineslx commented on python-clusters/create-gke-cluster/cluster.json
> +            "description": "[Optional] Range name or CIDR block/mask notation, e.g. 10.1.0.0/16 or /14. MUST not overlap with the subnet IP range. If using a named range, ensure it is at least as lar
not sure about this one

2023-08-10 07:07 UTC, marchelleboid commented on python-clusters/create-gke-cluster/cluster.json
> +            "description": "[Optional] Range name or CIDR block/mask notation, e.g. 10.1.0.0/16 or /14. MUST not overlap with the subnet IP range. If using a named range, ensure it is at least as lar
I left it as `/14` since that's what GKE chooses when you let it pick the range. But maybe it makes more sense to show `/16` as an example.

2023-08-10 09:25 UTC, amandineslx approved these changes
OK for me

different scenarios have been tested during first verification of the card and work well
this PR is only about hints and documentation and the code is now aligned with what works

2023-08-10 09:35 UTC, merged